
title: Kitae Kim
url: 'http://kimkt0408.github.io'
baseurl: '/kimkt0408.github.io' #change it according to your repository name



# Profile information
yourname: Kitae Kim  ## put your name
title: 'Master Degree Student'  ## your title
location: Korea University, Seoul, Korea


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
